#!/usr/bin/env python

from __future__ import print_function
import argparse
from builtins import input
from datetime import date, timedelta
#from redminelib import Redmine
from clockifytool.api import ClockifyApi
from slackclient import SlackClient
import os
import sys
import yaml


def preprocess_argv():
    # Remove script from argv
    argv = sys.argv[1:]

    if len(argv):
        command_abbreviations = {
            'p': 'preview'
        }

        if argv[0] in command_abbreviations:
            # Expand command abbreviation
            argv[0] = command_abbreviations[argv[0]]
    else:
        # Default to "list" command
        argv = ['yesterday']

    return argv


def arg_parser():
    """Return ArgumentParser for this application."""
    parser = argparse.ArgumentParser(description='Scrumpal.')
    subparsers = parser.add_subparsers(dest='command')

    parser_new = subparsers.add_parser('preview', help='Preview scrum report')
    parser_new = subparsers.add_parser('yesterday', help='Scrum report')

    return parser


def load_config():
    """Return configuration, from YAML file, for this application.
    Raises:
        Exception: If not able to read or parse the configuration file for any
                   reason or if "base branch" isn't set in the configuration
                   file.
    Returns:
        dict: Configuration information.
    """
    config_filename = '.scrumpal.yml'

    # Attempt to load configuration file from user's home directory
    config_path = os.path.join(os.path.expanduser('~'), config_filename)

    try:
        config = yaml.safe_load(open(config_path))
    except:
        raise Exception('Unable to load ~/{}: does it exist (or is there a YAML error)?'.format(config_filename))

    # Verify Clockify API key has been set in the config file
    if 'api key' not in config:
        raise Exception('Please set Clockify API key as "api key" in {}.'.format(config_filename))

    # Verify Clockify workspace ID in the config file
    if 'workspace' not in config:
        raise Exception('Please set Clockify workspace ID as "workspace" in {}.'.format(config_filename))

    return config


def bullet_point(description, project_or_task):
    if project_or_task:
        return '* {} ({})'.format(description, str(project_or_task)) + "\n"
    else:
        return '* {}'.format(description) + "\n"


# Parse CLI arguments
parser = arg_parser()
args = parser.parse_args(preprocess_argv())

# Load configuration
config = load_config()

# Authenticate
clockify = ClockifyApi(config['api key'])
clockify.set_workspace(config['workspace'])

days_back = 1
if args.command == 'preview':
    days_back = 0

yesterday_raw = date.today() - timedelta(days_back)
report_date = yesterday_raw.strftime('%Y-%m-%d')

print("Fetching time entries from {}...".format(report_date))
print()

# Get yesterday's time entries
time_entries = clockify.entries(start=report_date + 'T00:00:00', end=report_date + 'T23:59:59')

# Print scrum update template
report = "Since last scrum"
report += "\n----------------\n"

for entry in time_entries:
    if not 'projectId' in entry or not entry['projectId'] in config['ignore projects']:
        if 'project' in entry and 'name' in entry['project']:
            if entry['task']:
                project_name = entry['task']['name']
            else:
                project_name = entry['project']['name']

            report += bullet_point(entry['description'], project_name)
        else:
            report += bullet_point(entry['description'], False)

report += "\nNext"
report += "\n----\n"

# Display tasks, if any
if 'current tasks' in config and config['current tasks']:
    for task in config['current tasks']:
        report += bullet_point(task, False)

# Display blockers, if any
report += "\nBlockers"
report += "\n--------\n"

if 'blockers' in config and config['blockers']:
    for blocker in config['blockers']:
        report += bullet_point(blocker, False)
else:
    report += bullet_point('None', False)

print(report)

# Send report to Slack, if configured to do so
if 'slack api token' in config and config['slack api token']:
    print()
    input("Press [ENTER] to send report to Slack (or CTRL-C to cancel).")

    sc = SlackClient(config['slack api token'])

    sc.api_call(
        "chat.postMessage",
        channel=config['slack channel'],
        username=config['slack username'],
        as_user=True,
        text='```'+ report + '```'
    )

    print()
    print('Report sent to Slack.')
